# Uncomment the next line to define a global platform for your project

# platform :ios, '10.0'


target 'Viese' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'UnityAds'

  # Pods for Viese
  pod 'Alamofire'
  # Pods for Viese

  target 'VieseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VieseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

	
  


end
